# Generated by Django 4.2 on 2023-05-19 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customeToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('owner', models.OneToOneField(on_delete=django.db.models.expressions.Case, related_name='custom_token', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('authtoken.token',),
        ),
    ]
