# Generated by Django 4.2 on 2023-05-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='variant1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='questions',
            name='variant2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='questions',
            name='variant3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='questions',
            name='variant4',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='result',
            name='falseanswers',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='result',
            name='trueanswers',
            field=models.CharField(max_length=50),
        ),
    ]
