# Generated by Django 4.2 on 2023-04-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_category_categoryphone_categorybrand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorybrand',
            old_name='category_id',
            new_name='category',
        ),
    ]
