# Generated by Django 4.2 on 2023-04-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_models'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Brand',
        ),
    ]
