# Generated by Django 4.2 on 2023-04-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_phone_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='self'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Models',
        ),
    ]
