# Generated by Django 4.2 on 2023-04-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_category_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat',
            new_name='category_id',
        ),
    ]
