# Generated by Django 4.2 on 2023-04-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='cate',
        ),
    ]
