# Generated by Django 4.2 on 2023-04-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_category_id_categorybrand_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoryphone',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Categorybrand',
            new_name='Phone',
        ),
    ]
