# Generated by Django 4.2 on 2023-04-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_models_category_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childreb', to='app.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
