# Generated by Django 4.2 on 2023-05-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='write',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='app.writer'),
            preserve_default=False,
        ),
    ]
