# Generated by Django 4.2 on 2023-04-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Names',
        ),
    ]
