# Generated by Django 4.2 on 2023-04-26 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_cartname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_items',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.cart'),
            preserve_default=False,
        ),
    ]
