# Generated by Django 4.2 on 2023-04-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_cart_cartname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='about',
        ),
    ]
